# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen/popup_product_push.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PopupPushProduct(object):
    def setupUi(self, PopupPushProduct):
        PopupPushProduct.setObjectName("PopupPushProduct")
        PopupPushProduct.resize(1572, 966)
        PopupPushProduct.setStyleSheet("        background-color: transparent;")
        self.centralwidget = QtWidgets.QWidget(PopupPushProduct)
        self.centralwidget.setStyleSheet("/* SCROLL BARS */\n"
"        QScrollBar:horizontal {\n"
"            border: none;\n"
"            background: rgb(52, 59, 72);\n"
"            height: 14px;\n"
"            margin: 0px 21px 0 21px;\n"
"            border-radius: 0px;\n"
"        }\n"
"        QScrollBar::handle:horizontal {\n"
"            background: rgb(15, 170, 255);\n"
"            min-width: 25px;\n"
"            border-radius: 7px\n"
"        }\n"
"        QScrollBar::add-line:horizontal {\n"
"            border: none;\n"
"            background: rgb(55, 63, 77);\n"
"            width: 20px;\n"
"            border-top-right-radius: 7px;\n"
"            border-bottom-right-radius: 7px;\n"
"            subcontrol-position: right;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:horizontal {\n"
"            border: none;\n"
"            background: rgb(55, 63, 77);\n"
"            width: 20px;\n"
"            border-top-left-radius: 7px;\n"
"            border-bottom-left-radius: 7px;\n"
"            subcontrol-position: left;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"        {\n"
"            background: none;\n"
"        }\n"
"        QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"        {\n"
"            background: none;\n"
"        }\n"
"        QScrollBar:vertical {\n"
"            border: none;\n"
"            background: rgb(55, 63, 77);\n"
"            width: 24px;\n"
"                margin: 21px 0 21px 8px;\n"
"            border-radius: 0px;\n"
"        }\n"
"        QScrollBar::handle:vertical {    \n"
"            background: rgb(85, 170, 255);\n"
"            min-height: 25px;\n"
"            border-radius: 7px\n"
"        }\n"
"        QScrollBar::add-line:vertical {\n"
"            border: none;\n"
"            background: rgb(55, 63, 77);\n"
"            height: 20px;\n"
"            margin-left:8px;\n"
"            border-bottom-left-radius: 7px;\n"
"            border-bottom-right-radius: 7px;\n"
"            subcontrol-position: bottom;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::sub-line:vertical {\n"
"            border: none;\n"
"            background: rgb(55, 63, 77);\n"
"            height: 20px;\n"
"            margin-left:8px;\n"
"            border-top-left-radius: 7px;\n"
"            border-top-right-radius: 7px;\n"
"            subcontrol-position: top;\n"
"            subcontrol-origin: margin;\n"
"        }\n"
"        QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"            background: none;\n"
"        }\n"
"\n"
"\n"
"        QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"            background: none;\n"
"        }\n"
"\n"
"\n"
"        \n"
"        QTableWidget {    \n"
"            background-color: rgb(40, 44, 52);\n"
"            padding: 10px;\n"
"            border-radius: 18px;\n"
"            gridline-color: rgb(44, 49, 60);\n"
"            border-bottom: 1px solid rgb(44, 49, 60);\n"
"        }\n"
"        QTableWidget::item{\n"
"            border-color: rgb(44, 49, 60);\n"
"            padding-left: 5px;\n"
"            padding-right: 5px;\n"
"            gridline-color: rgb(44, 49, 60);\n"
"        }\n"
"        QTableWidget::item:selected{\n"
"            background-color: rgb(85, 170, 255);\n"
"        }\n"
"        QHeaderView::section{\n"
"            Background-color: rgb(39, 44, 54);\n"
"            max-width: 30px;\n"
"            border: 1px solid rgb(44, 49, 60);\n"
"            border-style: none;\n"
"            border-bottom: 1px solid rgb(44, 49, 60);\n"
"            border-right: 1px solid rgb(44, 49, 60);\n"
"        }\n"
"        QTableWidget::horizontalHeader {    \n"
"            background-color: rgb(81, 255, 0);\n"
"        }\n"
"        QHeaderView::section:horizontal\n"
"        {\n"
"            border: 1px solid rgb(32, 34, 42);\n"
"            background-color: rgb(27, 29, 35);\n"
"            padding: 3px;\n"
"            border-top-left-radius: 7px;\n"
"            border-top-right-radius: 7px;\n"
"        }\n"
"        QHeaderView::section:vertical\n"
"        {\n"
"            border: 1px solid rgb(44, 49, 60);\n"
"        }\n"
"\n"
"\n"
"        QPushButton {    \n"
"            border: none;\n"
"            background-color: transparent;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(89, 125, 245);\n"
"        }\n"
"        QPushButton:pressed {    \n"
"            background-color: rgb(85, 170, 255);\n"
"        }\n"
"\n"
"\n"
"        QFrame {\n"
"            background-color: rgb(40, 44, 52);\n"
"            color: rgb(210, 210, 210);\n"
"        }\n"
"\n"
"    QPushButton {\n"
"        border-radius: 4px;\n"
"        padding:8px 25px 7px 25px;\n"
"    background-color: rgb(64, 112, 244);\n"
"        color: rgb(255, 255, 255);\n"
"    }\n"
"    QPushButton:hover{\n"
"    background-color: rgb(107, 145, 250);\n"
"    }\n"
"    QPushButton:pressed{\n"
"    background-color: rgb(48, 103, 255);\n"
"    }\n"
"    QPushButton:disabled{\n"
"        background-color: rgb(128, 128, 128);\n"
"    }\n"
"\n"
"    #btn_cancel{\n"
"        background-color: rgb(249, 247, 250);\n"
"        color: rgb(14, 14, 14);\n"
"    }\n"
"\n"
"    #btn_cancel:hover{\n"
"        background-color: rgb(212, 211, 213);\n"
"    }\n"
"    #btn_cancel:pressed{\n"
"        background-color: rgb(48, 103, 255);\n"
"    }\n"
"\n"
"    QLineEdit {\n"
"    padding-left : 10px;\n"
"    border-radius: 2px;\n"
"    border: 1px solid rgb(210, 210, 210);\n"
"    color: rgb(210, 210, 210);\n"
"    }")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(31)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.searchLineEdit = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLineEdit.sizePolicy().hasHeightForWidth())
        self.searchLineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        self.searchLineEdit.setFont(font)
        self.searchLineEdit.setStyleSheet("")
        self.searchLineEdit.setInputMask("")
        self.searchLineEdit.setFrame(True)
        self.searchLineEdit.setPlaceholderText("")
        self.searchLineEdit.setClearButtonEnabled(False)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout_3.addWidget(self.searchLineEdit)
        self.btnSearch = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearch.sizePolicy().hasHeightForWidth())
        self.btnSearch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout_3.addWidget(self.btnSearch)
        self.horizontalLayout.addWidget(self.frame_3)
        self.btn_back = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_back.sizePolicy().hasHeightForWidth())
        self.btn_back.setSizePolicy(sizePolicy)
        self.btn_back.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.btn_forward = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_forward.sizePolicy().hasHeightForWidth())
        self.btn_forward.setSizePolicy(sizePolicy)
        self.btn_forward.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        self.btn_forward.setFont(font)
        self.btn_forward.setObjectName("btn_forward")
        self.horizontalLayout.addWidget(self.btn_forward)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.tableWidget_product_push_shopee = QtWidgets.QTableWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_product_push_shopee.sizePolicy().hasHeightForWidth())
        self.tableWidget_product_push_shopee.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        self.tableWidget_product_push_shopee.setFont(font)
        self.tableWidget_product_push_shopee.setStyleSheet("")
        self.tableWidget_product_push_shopee.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_product_push_shopee.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_product_push_shopee.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget_product_push_shopee.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_product_push_shopee.setAlternatingRowColors(False)
        self.tableWidget_product_push_shopee.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget_product_push_shopee.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_product_push_shopee.setRowCount(0)
        self.tableWidget_product_push_shopee.setColumnCount(8)
        self.tableWidget_product_push_shopee.setObjectName("tableWidget_product_push_shopee")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product_push_shopee.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_product_push_shopee.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_product_push_shopee.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_product_push_shopee.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_product_push_shopee.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_product_push_shopee.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_product_push_shopee.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_product_push_shopee.setHorizontalHeaderItem(7, item)
        self.tableWidget_product_push_shopee.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_product_push_shopee.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_product_push_shopee.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget_product_push_shopee.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_product_push_shopee.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_product_push_shopee.verticalHeader().setVisible(False)
        self.tableWidget_product_push_shopee.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_product_push_shopee.verticalHeader().setHighlightSections(False)
        self.tableWidget_product_push_shopee.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.tableWidget_product_push_shopee)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.btn_cancel = QtWidgets.QPushButton(self.frame_4)
        self.btn_cancel.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(18)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.btn_confirm = QtWidgets.QPushButton(self.frame_4)
        self.btn_confirm.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(18)
        self.btn_confirm.setFont(font)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout_2.addWidget(self.btn_confirm)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        PopupPushProduct.setCentralWidget(self.centralwidget)

        self.retranslateUi(PopupPushProduct)
        QtCore.QMetaObject.connectSlotsByName(PopupPushProduct)

    def retranslateUi(self, PopupPushProduct):
        _translate = QtCore.QCoreApplication.translate
        PopupPushProduct.setWindowTitle(_translate("PopupPushProduct", "MainWindow"))
        self.label.setText(_translate("PopupPushProduct", "Chọn Sản Phẩm"))
        self.btnSearch.setText(_translate("PopupPushProduct", "Tìm kiếm"))
        self.btn_back.setText(_translate("PopupPushProduct", "<"))
        self.btn_forward.setText(_translate("PopupPushProduct", ">"))
        item = self.tableWidget_product_push_shopee.horizontalHeaderItem(1)
        item.setText(_translate("PopupPushProduct", "Hình ảnh"))
        item = self.tableWidget_product_push_shopee.horizontalHeaderItem(2)
        item.setText(_translate("PopupPushProduct", "Tên sản phẩm"))
        item = self.tableWidget_product_push_shopee.horizontalHeaderItem(3)
        item.setText(_translate("PopupPushProduct", "SKU"))
        item = self.tableWidget_product_push_shopee.horizontalHeaderItem(4)
        item.setText(_translate("PopupPushProduct", "Số lượng"))
        item = self.tableWidget_product_push_shopee.horizontalHeaderItem(5)
        item.setText(_translate("PopupPushProduct", "Giá thường"))
        item = self.tableWidget_product_push_shopee.horizontalHeaderItem(6)
        item.setText(_translate("PopupPushProduct", "Giá SALE"))
        item = self.tableWidget_product_push_shopee.horizontalHeaderItem(7)
        item.setText(_translate("PopupPushProduct", "Đã bán"))
        self.btn_cancel.setText(_translate("PopupPushProduct", "Thoát"))
        self.btn_confirm.setText(_translate("PopupPushProduct", "Thêm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PopupPushProduct = QtWidgets.QMainWindow()
    ui = Ui_PopupPushProduct()
    ui.setupUi(PopupPushProduct)
    PopupPushProduct.show()
    sys.exit(app.exec_())
