# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen/signin_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from . resources_rc import *

class Ui_SignInScreen(object):
    def setupUi(self, SignInScreen):
        SignInScreen.setObjectName("SignInScreen")
        SignInScreen.resize(1416, 775)
        SignInScreen.setMinimumSize(QtCore.QSize(940, 560))
        self.centralwidget = QtWidgets.QWidget(SignInScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("background-color: rgb(75, 34, 169);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(50, -1, 50, -1)
        self.verticalLayout.setSpacing(23)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_6.setStyleSheet("image: url(:/images/images/images/logo_long_full_white.png);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(1)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout.addWidget(self.frame_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAcceptDrops(False)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.signupBtn = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signupBtn.sizePolicy().hasHeightForWidth())
        self.signupBtn.setSizePolicy(sizePolicy)
        self.signupBtn.setMinimumSize(QtCore.QSize(300, 60))
        self.signupBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.signupBtn.setFont(font)
        self.signupBtn.setAutoFillBackground(False)
        self.signupBtn.setStyleSheet("QPushButton{\n"
"    border-radius: 30px;\n"
"    padding:8px 25px 7px 25px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(89, 64, 231, 255), stop:1 rgba(15, 181, 253, 255));\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 181, 253, 255), stop:1 rgba(89, 64, 231, 255));\n"
"}")
        self.signupBtn.setAutoDefault(False)
        self.signupBtn.setDefault(False)
        self.signupBtn.setFlat(False)
        self.signupBtn.setObjectName("signupBtn")
        self.verticalLayout.addWidget(self.signupBtn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(74, 50, 201);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(50, 50, 50, 90)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setStyleSheet("image: url(:/images/images/images/logo_only_white.png);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2.addWidget(self.frame_4)
        self.dang_nhap = QtWidgets.QLabel(self.frame_2)
        self.dang_nhap.setMaximumSize(QtCore.QSize(190000, 50))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.dang_nhap.setFont(font)
        self.dang_nhap.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.dang_nhap.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dang_nhap.setScaledContents(False)
        self.dang_nhap.setAlignment(QtCore.Qt.AlignCenter)
        self.dang_nhap.setObjectName("dang_nhap")
        self.verticalLayout_2.addWidget(self.dang_nhap)
        self.username = QtWidgets.QLineEdit(self.frame_2)
        self.username.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.username.setFont(font)
        self.username.setMouseTracking(True)
        self.username.setStyleSheet("QLineEdit{\n"
"    margin-left : 20px;    \n"
"    margin-right : 20px;    \n"
"    background-color: rgba(255, 255, 255, 217);\n"
"    padding-left : 15px;\n"
"    border-radius:30px;\n"
"    border: 2px solid rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(90,90,90);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(90,90,90);\n"
"}\n"
"")
        self.username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username.setDragEnabled(False)
        self.username.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.username.setObjectName("username")
        self.verticalLayout_2.addWidget(self.username)
        self.password = QtWidgets.QLineEdit(self.frame_2)
        self.password.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setMouseTracking(True)
        self.password.setStyleSheet("QLineEdit{\n"
"    margin-left : 20px;    \n"
"    margin-right : 20px;    \n"
"    background-color: rgba(255, 255, 255, 217);\n"
"    padding-left : 15px;\n"
"    border-radius: 30px;\n"
"    border: 2px solid rgb(45,45,45);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(90,90,90);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(90,90,90);\n"
"}\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setDragEnabled(False)
        self.password.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.password.setObjectName("password")
        self.verticalLayout_2.addWidget(self.password)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.savePassCheckBox = QtWidgets.QCheckBox(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.savePassCheckBox.setFont(font)
        self.savePassCheckBox.setStyleSheet("QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    margin-left : 30px;    \n"
"    margin-right : 30px;    \n"
"}\n"
"\n"
"QCheckBox:indicator {\n"
"    border : 3px solid rgb(100,100,100);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    margin-right: 10px\n"
"}\n"
"QCheckBox:indicator:checked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.savePassCheckBox.setIconSize(QtCore.QSize(16, 16))
        self.savePassCheckBox.setTristate(False)
        self.savePassCheckBox.setObjectName("savePassCheckBox")
        self.horizontalLayout_5.addWidget(self.savePassCheckBox)
        self.resetPasswordBtn = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.resetPasswordBtn.setFont(font)
        self.resetPasswordBtn.setStyleSheet("background-color: rgba(254, 253, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.resetPasswordBtn.setObjectName("resetPasswordBtn")
        self.horizontalLayout_5.addWidget(self.resetPasswordBtn)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.signinBtn = QtWidgets.QPushButton(self.frame_2)
        self.signinBtn.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Nunito")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.signinBtn.setFont(font)
        self.signinBtn.setStyleSheet("QPushButton{\n"
"    border-radius: 30px;\n"
"    padding:8px 25px 7px 25px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(89, 64, 231, 255), stop:1 rgba(15, 181, 253, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    margin-left : 30px;    \n"
"    margin-right : 30px;    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(15, 181, 253, 255), stop:1 rgba(89, 64, 231, 255));\n"
"}")
        self.signinBtn.setObjectName("signinBtn")
        self.verticalLayout_2.addWidget(self.signinBtn)
        self.horizontalLayout.addWidget(self.frame_2)
        SignInScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SignInScreen)
        QtCore.QMetaObject.connectSlotsByName(SignInScreen)

    def retranslateUi(self, SignInScreen):
        _translate = QtCore.QCoreApplication.translate
        SignInScreen.setWindowTitle(_translate("SignInScreen", "MainWindow"))
        self.label_2.setText(_translate("SignInScreen", "Ứng Dụng"))
        self.label_4.setText(_translate("SignInScreen", "QUẢN LÝ BÁN HÀNG"))
        self.label_5.setText(_translate("SignInScreen", "Công cụ giúp bạn quản lý thật nhanh và đơn giản các kênh bán hàng thương mại điện tử như Shopee, Lazada, Tiki, Sendo ..."))
        self.signupBtn.setText(_translate("SignInScreen", "ĐĂNG KÝ"))
        self.dang_nhap.setText(_translate("SignInScreen", "ĐĂNG NHẬP"))
        self.username.setPlaceholderText(_translate("SignInScreen", "Username"))
        self.password.setPlaceholderText(_translate("SignInScreen", "Password"))
        self.savePassCheckBox.setText(_translate("SignInScreen", "Nhớ mật khẩu"))
        self.resetPasswordBtn.setText(_translate("SignInScreen", "Quên mật khẩu ?"))
        self.signinBtn.setText(_translate("SignInScreen", "ĐĂNG NHẬP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignInScreen = QtWidgets.QMainWindow()
    ui = Ui_SignInScreen()
    ui.setupUi(SignInScreen)
    SignInScreen.show()
    sys.exit(app.exec_())
